&"$PSScriptRoot\Steps\Deactivate-PART1.ps1"
&"$PSScriptRoot\Steps\Deactivate-PART2.ps1"
&"$PSScriptRoot\Steps\Deactivate-PART3.ps1"
&"$PSScriptRoot\Steps\Deactivate-PART4.ps1"
&"$PSScriptRoot\Steps\Deactivate-PART5.ps1"
